In [1]:
########## Import Libararies
import os
import pickle
import glob
from tqdm.notebook import tqdm

import numpy as np
from skimage import measure
import scipy.ndimage
import matplotlib.pyplot as plt
from matplotlib import rc
%matplotlib inline

import open3d as o3d
from compas.geometry import trimesh_remesh
from compas.datastructures import Mesh
import nibabel as nib

from util import *

import csv
import copy

def read_csv_to_dict(file_path):

    data_dict = {}
    with open(file_path, mode='r', newline='', encoding='utf-8', errors='ignore') as file:
        reader = csv.reader(file)
        
        headers = next(reader)  # assuming first row contains headers
        
        for row in reader:
            # print(row)
            key = row[0]  # Assuming the first column is the key
            values = row[1:]  # Assuming the rest of the columns are values
            data_dict[key] = values
            
    return data_dict

def read_local_deformity(file_path):
# Read the content of the text file
    with open(file_path, 'r') as file:
        content = file.read()
    entries = content.split('***')
    data = {}

    for entry in entries:

        parts = entry.split(' ')
        key = parts[0]
        values = parts[1:4003]
        values_array = np.array([float(v) for v in values])
        data[key] = values_array

    return data
######### Read Hippo Temp Mesh #########
excel_dir = r"D:\Data-to-KAIST\Task1) cross-hippo\edinburgh\common_wj_jerry_Cognition_measures_LBC1936_w2.csv"
past_excel = read_csv_to_dict(excel_dir)
print(past_excel.keys())
# print((WJ_deform['360002_R']),len((WJ_deform['360002_R'])))

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed')).History will not be written to the database.
Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
dict_keys(['LBC360002', 'LBC360003', 'LBC360004', 'LBC360006', 'LBC360007', 'LBC360008', 'LBC360009', 'LBC360013', 'LBC360015', 'LBC360017', 'LBC360020', 'LBC360021', 'LBC360022', 'LBC360023', 'LBC360026', 'LBC360029', 'LBC360030', 'LBC360031', 'LBC360032', 'LBC360034', 'LBC360036', 'LBC360038', 'LBC360041', 'LBC360042', 'LBC360045', 'LBC360048', 'LBC360051', 'LBC360052', 'LBC360055', 'LBC360056', 'LBC360058', 'LBC360059', 'LBC360061', 'LBC360063', 'LBC360066', 'LBC360067', 'LBC360069', 'LBC360072', 'LBC360074', 'LBC360076', 'LBC360079', 'LBC360081', 'LBC360083', 'LBC360085', 'LBC360087', 'LBC360089', 'LBC360091', 'LBC360092', 'LBC360097', 'LBC360100', 'LBC360102', 'LBC360104

In [52]:
modes = ["l","r"]#,"synthseg_l_new_4002","synthseg_r_new_4002","synthseg_l_old","synthseg_r_old"]#"synthseg_l_new_2001","synthseg_r_new_2001"]#
import os
for mode in modes:
    for i_tag in range(1):
        print(mode)
        if i_tag ==0:
            WJ_deform = read_local_deformity(rf"D:\IdeaProjects\IITP_synth\lv-parametric-modelling\ipynb\edinburgh_longi_hippo\LocalDeformity_Jerry{mode}.txt")
        else:
            WJ_deform = read_local_deformity(rf"C:\Users\v1wpark\Documents\Projects\lv-parametric-modelling\ipynb\edinburgh\LocalDeformity_{mode}_jerry.txt")

        new_dict ={}
        
        for key in WJ_deform.keys():
            new_key = key[3:]#"LBC"+key.split("_")[0]
            new_dict[new_key] = WJ_deform[key]
            # print(new_dict[new_key])
        WJ_deform = new_dict
        print(new_key)
        import numpy as np

        # For debugging purposes
        sub_ids = os.listdir(r"D:\Data-to-KAIST\Task3) longi-hippo\hippo\Scan1")

        not_in =[]
        # Open the file in append mode
        count=0
        if i_tag==0: filenametxt= rf'ordered_Jerry{mode}.txt'
        else: filenametxt=rf'ordered_{mode}_jerry.txt'
        with open(filenametxt, 'a') as f:
            for key in tqdm(past_excel.keys()):
                sub_id = key[3:]
                if "l" in mode:
                    f.write(f"{sub_id}_L ")
                elif "r" in mode:
                    f.write(f"{sub_id}_R ")
                
                print(WJ_deform[str(sub_id)])

                np.savetxt(f, np.asarray(WJ_deform[sub_id]), fmt='%.5f', delimiter=' ', newline=' ')
                f.write(f"***")
                count+=1
        print(count)

l



  3%|▎         | 17/604 [00:00<00:03, 168.32it/s]

[1.14763 1.18982 1.17089 ... 2.69268 2.66513 2.63961]
[ 3.43017  3.43283  3.38852 ... -4.06742 -4.16726 -4.25553]
[-0.45277 -0.30465 -0.32863 ...  0.67003  0.6721   0.68865]
[ 1.07276 -0.99118  1.0325  ... -1.07486 -1.09394 -1.09302]
[-1.50647 -1.62083 -1.5764  ...  2.89114  2.87342  2.86825]
[2.38485 2.30399 2.33723 ... 1.21133 1.20558 1.22704]
[-1.56217 -1.62733 -1.55441 ...  2.49957  2.49951  2.49917]
[ 5.62675  5.44571  5.44626 ... -6.5382  -6.71974 -6.80115]
[-0.81365 -0.89227 -0.9197  ...  1.16784  1.05449  0.98776]
[-0.83664 -0.90544 -0.84855 ...  3.0184   3.04106  3.12818]
[-0.87047 -0.91115 -0.85422 ...  2.35685  2.33342  2.30811]
[-0.89525 -0.89981 -0.88237 ...  1.15386  1.20577  1.30137]
[-0.98529 -1.05388 -1.04306 ...  1.33453  1.3063   1.27635]
[-2.32821 -2.26863 -2.31822 ...  1.60712  1.5898   1.59222]
[0.69046 0.57353 0.62862 ... 1.24156 1.18528 1.17432]
[-2.25279 -2.22358 -2.23477 ... -2.36053  2.34876  2.33915]
[-0.96485 -0.93555 -0.88528 ...  1.09649 -1.09928 -1.12842

  8%|▊         | 51/604 [00:00<00:03, 166.29it/s]

[2.0565  2.00293 2.03983 ... 1.85939 1.82857 1.79965]
[-1.23579 -1.17493 -1.19164 ...  1.58132  1.52309  1.48201]
[-1.35501 -1.12691 -1.14017 ...  1.48965  1.59221  1.77342]
[-1.34424 -1.23796 -1.3018  ...  0.69626 -0.67903  0.70041]
[-0.92619 -0.88398 -0.79549 ...  1.73647  1.71253  1.70868]
[-2.41417 -2.47324 -2.45759 ... -2.36901 -2.3446  -2.32616]
[-3.19796 -3.22107 -3.17802 ...  4.06571  4.06764  4.04687]
[2.25474 2.21058 2.20344 ... 2.07896 2.00621 1.9225 ]
[-4.58118 -4.58705 -4.57073 ... -5.29152 -5.33301 -5.37269]
[-1.51528 -1.38405 -1.34126 ...  1.09475  1.07821 -1.07983]
[-1.43167  1.36886  1.3252  ... -1.28051 -1.21764 -1.21287]
[-0.87475 -0.923   -0.89177 ...  1.60479  1.61504  1.59982]
[ 1.64499  1.52725  1.551   ...  0.8628  -0.82993 -0.82162]
[5.75507 5.75182 5.6787  ... 7.40007 7.41485 7.41067]
[1.08313 0.99361 1.0224  ... 0.56245 0.60144 0.64965]
[-5.33561 -5.49316 -5.41357 ... -7.65181 -7.67967 -7.6929 ]
[0.94542 1.56473 1.51045 ... 1.58166 1.75317 1.97654]
[0.48677 0

 17%|█▋        | 102/604 [00:00<00:03, 165.57it/s]

[3.34811 3.38183 3.41778 ... 5.03667 4.98146 4.92038]
[-0.72838 -1.01696 -0.83142 ...  1.50202  1.3907   1.31714]
[ 1.9197   1.84527  1.80496 ... -2.17544 -2.17317 -2.17481]
[ 3.26927 -3.34479  3.29485 ...  4.96124  4.97313  4.97132]
[2.318   2.48218 2.44398 ... 4.06709 4.04066 4.00913]
[-2.00333 -2.09086 -2.03668 ...  3.89978  3.88358  3.86383]
[-1.17034 -1.20318 -1.1733  ...  2.40495  2.40641  2.40423]
[ 5.11329  5.07029  5.07395 ... -5.17354 -5.2417  -5.29257]
[-3.24922 -3.26642 -3.21582 ... -4.29742 -4.27188 -4.24079]
[-0.94233 -0.91478 -0.86872 ...  1.16264  0.92581  0.72677]
[1.96104 2.12514 2.09692 ... 3.74813 3.5706  3.46748]
[-3.56439  3.62555  3.56716 ... -4.26882 -4.27426  4.2771 ]
[-1.24175 -1.08365 -1.07865 ...  1.19916  1.26216  1.33379]
[-0.92329 -0.98712 -0.88395 ...  1.51145  1.46481  1.45218]
[-2.06787 -2.02954 -2.0219  ... -2.61287 -2.63517 -2.66306]
[-1.19147 -1.20334 -1.17114 ...  2.757    2.68296  2.64462]
[ 1.65264  1.68702  1.6829  ... -3.108   -3.09228 -3.06118

 23%|██▎       | 136/604 [00:00<00:02, 164.02it/s]

[ 2.25172  2.1992   2.17773 ... -3.02285 -3.00641 -3.02924]
[ 1.23956  1.16411  1.12229 ... -1.38149 -1.42338 -1.45712]
[5.04685 5.05973 5.04638 ... 5.79003 5.71641 5.67098]
[-1.28109 -1.18135 -1.22091 ... -0.57799  0.59188  0.63272]
[  9.82246   9.73788   9.64548 ... -12.4726  -12.47682 -12.4712 ]
[-0.7118  -0.91337  0.90304 ...  2.01363  2.04205  2.04723]
[-0.31908 -0.43697 -0.35544 ...  1.4995   1.44888  1.37877]
[ 3.11881  3.11701  3.1141  ... -3.68688 -3.67984 -3.65838]
[-1.08491 -1.07714 -1.08181 ...  0.68515  0.72917  0.7233 ]
[8.03971 7.91431 7.92207 ... 8.603   8.60956 8.5866 ]
[-2.58435 -2.60809 -2.59356 ...  2.78769  2.78823  2.78679]
[-2.39169 -2.36859 -2.36577 ...  1.86179  1.88309  1.91901]
[-0.51003 -0.4877  -0.52619 ...  1.64295  1.71631  1.76476]
[-1.26015 -1.288   -1.24852 ... -1.63042 -1.64572 -1.67766]
[-0.42644 -0.35362 -0.45506 ...  0.68621  0.72612  0.75609]
[-1.01875 -0.98454 -1.03271 ...  1.16039  1.10758  1.06112]
[1.2148  1.0986  1.13582 ... 0.942   0.97022 1

 28%|██▊       | 170/604 [00:01<00:02, 165.38it/s]

[-0.45009 -0.41199 -0.44548 ...  1.2595   1.42597  1.55625]
[ 2.37895  2.3388   2.32189 ... -2.91643 -2.88094 -2.85733]
[-0.93008 -0.87711 -0.81949 ...  0.71662  0.71273  0.7148 ]
[1.65804 1.65808 1.60609 ... 2.27673 2.30994 2.41616]
[-0.71784 -0.67913 -0.62387 ...  1.3262   1.3053   1.31615]
[-2.89832 -2.93049 -2.92397 ...  3.98043  3.97735  3.985  ]
[-3.30496 -3.17012 -3.26549 ... -4.59797 -4.59347 -4.58363]
[ 4.43197  4.37874  4.36521 ... -4.26814 -4.30671 -4.3665 ]
[ 1.50851  1.39147  1.39761 ...  1.15228 -1.06776 -1.0292 ]
[-1.11764 -1.25243 -1.20885 ...  3.52906  3.5007   3.42605]
[-0.69769 -0.676   -0.77949 ...  1.88096  1.86422  1.92131]
[4.02432 4.03771 3.98659 ... 5.62353 5.70776 5.81228]
[-2.78228  2.71981  2.73008 ... -2.97487 -2.98275 -2.98596]
[-1.34337 -1.36808 -1.28567 ...  2.98226  3.02681  3.06516]
[-1.19045 -1.17492 -1.11391 ...  1.72779  1.69261  1.66592]
[-0.89565 -0.98801 -0.93171 ...  1.74492  1.83787  1.97208]
[ 1.61303 -1.7962  -1.76222 ...  3.02499  3.00946  2

 31%|███       | 187/604 [00:01<00:02, 163.72it/s]

[ 2.61559  2.52938  2.38827 ... -4.0763  -4.21611 -4.3476 ]
[ 1.22622  1.30533  1.27297 ... -2.74629 -2.98912 -3.33918]
[7.52855 7.42577 7.40777 ... 8.60978 8.53578 8.46604]
[-0.69332 -0.8396  -0.79196 ...  1.09337  1.0187   1.00444]
[7.57869 7.55665 7.50319 ... 9.84294 9.80149 9.76563]
[-2.13108 -2.08991 -2.0604  ... -1.77954 -1.82755 -1.92677]
[-0.76366 -0.69237 -0.71649 ...  0.68288  0.71996  0.73555]
[1.77846 1.68081 1.68687 ... 1.64462 1.6711  1.70173]
[0.94335 1.00267 0.981   ... 2.60338 2.5557  2.4877 ]
[-3.54715 -3.70985 -3.65571 ...  4.26964  4.30198  4.39578]
[ 8.06328  7.91303  7.90224 ... -9.5057  -9.50305 -9.48737]
[-0.79543 -0.84581 -0.83253 ...  1.64814  1.63352  1.62469]
[1.19223 1.23578 1.21229 ... 2.58832 2.59187 2.64051]
[ 0.86545 -0.97404 -0.97756 ... -2.3083  -2.29877 -2.27973]
[-1.00844 -0.98397 -0.9115  ...  1.82174  1.88835  1.8924 ]
[-4.56308 -4.52896 -4.46759 ...  6.41538  6.38512  6.34925]
[7.1134  7.04666 6.98356 ... 8.6855  8.65439 8.64079]
[ 2.61114  2.547

 39%|███▉      | 238/604 [00:01<00:02, 164.38it/s]

[-0.68627 -0.66338 -0.65306 ...  1.03079  1.05285  1.12092]
[ 1.77505  1.73632  1.70966 ... -1.91028 -1.96376 -1.98992]
[ 2.93187  2.98658  2.94342 ... -4.70576 -4.72294 -4.73402]
[-1.44828 -1.71132 -1.73841 ...  2.30557  2.26672  2.22682]
[-3.7233  -3.73049 -3.69899 ... -4.45447 -4.48122 -4.47838]
[-1.69907 -1.66132 -1.61124 ... -2.07261 -2.10498 -2.12533]
[ 1.69207  1.6247   1.63215 ... -1.46509 -1.53922 -1.62959]
[ 5.69742  5.64788  5.6419  ... -6.42625 -6.42963 -6.43295]
[ 1.83148 -1.72422 -1.76011 ... -1.65209 -1.65666 -1.66148]
[-2.13116 -2.11569 -2.15259 ... -2.11234 -2.10117 -2.09204]
[2.39409 2.59977 2.5162  ... 4.6706  4.67026 4.74073]
[4.7324  4.70163 4.67497 ... 5.2098  5.23845 5.27089]
[0.44723 0.51275 0.40977 ... 0.81341 0.82197 0.78142]
[-3.83277  3.81928 -3.80801 ... -5.23259 -5.23572 -5.22408]
[7.85634 7.77855 7.73308 ... 9.42536 9.55161 9.62565]
[-2.09822 -2.12071 -2.12511 ...  1.3184   1.28092  1.26261]
[-0.36579 -0.42462 -0.44676 ...  0.45137  0.37737  0.32372]
[3.8

 42%|████▏     | 255/604 [00:01<00:02, 165.06it/s]

[-0.37604 -0.40922 -0.38384 ...  0.90515  0.91223  0.87118]
[ 1.64862 -1.80258 -1.84592 ...  2.60709  2.60966  2.58595]
[ 4.57852  4.60362  4.58037 ... -5.67416 -5.60804 -5.57367]
[1.02393 0.73695 0.85345 ... 1.09878 1.03148 0.99138]
[-6.83495 -7.05067 -7.01286 ... -7.59395 -7.59369 -7.59623]
[4.32467 4.28132 4.23177 ... 4.72736 4.85254 4.89157]
[-0.87806 -0.87577 -0.84229 ...  1.35436  1.46658  1.56302]
[-2.65561 -2.70153 -2.64975 ... -3.4136  -3.44479 -3.44115]
[7.27686 7.26245 7.20046 ... 8.2103  8.23436 8.26264]
[-2.75285 -2.74251 -2.71201 ... -2.72113 -2.77175 -2.81452]
[-1.42692  1.35431 -1.35382 ...  1.36147  1.31684  1.27426]
[-1.71045 -1.64203 -1.72446 ...  1.13818  1.11464  1.08804]
[-3.33789 -3.25803 -3.29966 ...  2.9092   2.92121  2.9246 ]
[-0.35823 -0.43906 -0.38519 ...  0.61056  0.652    0.69076]
[5.90913 5.85665 5.82668 ... 6.32736 6.38647 6.44104]
[-0.66627 -0.73591 -0.79062 ... -0.4496  -0.40271 -0.38924]
[ 5.70137  5.893    5.81216 ... -4.95829 -5.05627 -5.15462]
[-0.

 48%|████▊     | 289/604 [00:01<00:01, 165.52it/s]

[ 2.45653  2.46773  2.45548 ... -3.19268 -3.18402 -3.16835]
[-1.47538 -1.45847 -1.49242 ... -2.10866 -2.12758 -2.13734]
[-4.374   -4.41202 -4.40012 ... -5.13681 -5.11006 -5.08528]
[7.59555 7.50631 7.48589 ... 9.33602 9.28582 9.24995]
[-2.16145 -2.10663 -2.10866 ...  1.61312  1.64964  1.68565]
[2.71437 2.70781 2.67959 ... 2.89586 2.94084 3.01096]
[-1.78936 -1.79433 -1.79516 ... -2.30638 -2.32211 -2.3278 ]
[6.3175  6.21091 6.21255 ... 5.91802 5.94294 5.94596]
[-2.14863 -2.09455 -2.09933 ...  1.96129  1.88823  1.77329]
[-1.06419 -1.12118 -1.13941 ...  2.05973  2.06779  2.11126]
[1.68222 1.66176 1.65733 ... 2.18246 2.18496 2.15526]
[-3.67004 -3.57896 -3.61008 ... -3.43054 -3.42309 -3.43406]
[-2.32053 -2.27612 -2.25316 ...  1.95622  2.02552  2.09029]
[-2.06558 -2.08049 -2.05902 ... -3.17786 -3.12299 -3.07542]
[-1.86964 -1.88566 -1.8684  ... -2.47098 -2.47393 -2.48876]
[-2.86799 -2.87286 -2.84646 ... -3.90216 -3.91597 -3.92363]
[-2.67523 -2.68795 -2.62269 ... -3.12008 -3.15024 -3.17604]
[-1.

 53%|█████▎    | 323/604 [00:01<00:01, 164.80it/s]

[ 3.32328  3.34169  3.2966  ...  4.33735 -4.31592 -4.299  ]
[7.28486 7.26333 7.19932 ... 9.05134 9.15134 9.24042]
[ 8.9851   8.74433  8.74392 ... -9.11471 -9.0876  -9.06665]
[ 2.56381  2.51939  2.48597 ... -3.34444 -3.37899 -3.40429]
[ 3.07971  3.08921  3.07251 ... -3.91695 -3.89997 -3.88656]
[-0.58102 -0.7731  -0.77515 ...  1.11166  1.11878  1.12336]
[2.4563  2.48584 2.4099  ... 3.18432 3.15425 3.12843]
[7.01914 6.91599 6.89956 ... 7.89222 7.89616 7.88785]
[-1.62834 -1.66025 -1.64823 ... -1.9647  -1.96906 -1.97971]
[-1.5505  -1.5748  -1.62274 ... -2.1873  -2.17023 -2.15253]
[ 1.31358 -1.20416  1.23975 ...  1.56786  1.5081   1.46483]
[-1.99558 -2.08118 -2.04226 ... -3.29022 -3.34625 -3.36993]
[-2.48157 -2.45246 -2.49596 ... -2.01259 -1.97145 -1.91674]
[-4.871   -4.92962 -4.94208 ... -5.26643 -5.2142  -5.17911]
[-0.60925 -0.77723 -0.73406 ... -1.19483 -1.14723 -1.12391]
[ 5.29474  5.33036  5.2715  ... -7.00658 -7.062   -7.05719]
[-6.59527 -6.51922 -6.45187 ...  7.82383  7.84474  7.85889

 59%|█████▉    | 357/604 [00:02<00:01, 157.32it/s]

[1.10004 1.03812 0.98508 ... 0.81773 0.83407 0.87194]
[0.46509 0.52889 0.50575 ... 1.89218 1.86453 1.85956]
[-2.7627  -2.80863 -2.83581 ... -3.80358 -3.80814 -3.79586]
[ 9.06675  8.97079  8.93415 ... 10.58043 10.56972 10.56819]
[-2.96782  2.93477  2.89696 ...  4.14645  4.10424  4.0657 ]
[-1.4279  -1.49581 -1.52474 ... -2.50624 -2.48337 -2.45598]
[-1.38458 -1.37207 -1.38547 ...  0.75287  0.76745  0.78342]
[6.44456 6.32356 6.31795 ... 6.60413 6.58072 6.55268]
[ 1.59123 -1.65357 -1.61742 ... -2.51552 -2.54882 -2.56296]
[-1.05569 -1.12883 -1.07418 ...  2.24245  2.22203  2.20973]
[0.58309 0.58297 0.59869 ... 1.83409 1.72563 1.59552]
[-1.37682 -1.29178 -1.31735 ...  0.87988  0.82646  0.80012]
[ 3.18156  3.18047  3.17727 ...  4.01824 -3.98633 -3.95997]
[0.85378 0.85048 0.88509 ... 1.63073 1.63214 1.6415 ]
[ 3.26877 -3.36146 -3.30362 ... -5.00977 -5.07382 -5.14322]
[2.57799 2.52248 2.56609 ... 1.52788 1.51153 1.49924]
[-3.61244 -3.58129 -3.59327 ...  4.42093  4.45485  4.47951]
[5.64816 5.59436

 65%|██████▍   | 391/604 [00:02<00:01, 160.51it/s]

[ 2.85191  2.85076  2.80267 ... -3.87695 -3.89084 -3.89455]
[-4.34514 -4.40647 -4.33136 ... -6.25274 -6.2836  -6.30126]
[ 4.59227  4.57517  4.55799 ... -5.99972 -6.03512 -6.05805]
[ 6.43894 -6.32915 -6.28366 ...  7.75699  7.87857  7.98026]
[ 2.99049  2.98438  2.95056 ... -4.04363 -4.06268 -4.07677]
[6.98974 6.8871  6.88491 ... 7.46352 7.40321 7.36216]
[ 0.44276  0.41996  0.40714 ...  0.91974  0.88347 -0.86439]
[-2.22752 -2.21697 -2.24348 ... -2.96403  2.94367  2.94161]
[-2.15809 -2.16549 -2.17797 ...  2.33557  2.34746  2.36262]
[8.1717  8.13287 8.06616 ... 9.89829 9.89086 9.90216]
[-3.05174 -3.00354 -3.03614 ... -3.63203 -3.62394 -3.61756]
[-4.01965 -4.03429 -4.00745 ... -5.27716 -5.2753  -5.27331]
[3.14225 3.05353 3.00351 ... 3.40681 3.47379 3.51476]
[ 1.0097   0.92355  0.94066 ... -1.69186 -1.6871  -1.68391]
[ 3.31371 -3.23126  3.2784  ...  2.9864   2.94282  2.89046]
[-1.77193 -1.83976 -1.90449 ... -2.48855 -2.50779 -2.52581]
[-3.08614  3.09342  3.04964 ... -4.98104 -4.99482 -4.97657

 73%|███████▎  | 442/604 [00:02<00:00, 164.98it/s]

[4.95951 4.88536 4.90433 ... 4.50773 4.50084 4.50276]
[-2.80006 -2.75437 -2.73024 ...  3.32388  3.3128   3.31192]
[2.30933 2.34157 2.29374 ... 3.67124 3.71605 3.74401]
[ 3.21816 -3.17019 -3.14339 ...  3.07341  3.06154  3.04673]
[-3.1104  -3.09071 -3.09982 ...  2.41788  2.38397  2.35684]
[-0.87485 -0.97283 -0.87241 ...  1.54846  1.5036   1.51053]
[ 3.21629  3.22723  3.1756  ... -3.9985  -4.01231 -4.02018]
[-1.26007 -1.32815 -1.27901 ... -1.76582 -1.734   -1.69463]
[-0.90046 -0.95349 -0.89922 ...  2.46249  2.53428  2.55402]
[ 1.72707 -1.71855 -1.72605 ...  1.75057  1.66074  1.60107]
[4.39991 4.30945 4.32165 ... 5.30998 5.28447 5.24229]
[8.63495 8.49376 8.48398 ... 9.71185 9.64614 9.58503]
[ 1.45663  1.36273  1.37781 ... -2.25336 -2.21705 -2.17901]
[-0.68005  0.63951  0.71214 ... -0.78944 -0.73426 -0.72888]
[-1.61316 -1.6848  -1.68099 ... -2.87187 -2.91461 -2.94226]
[-2.3558  -2.35852 -2.35094 ... -2.34437 -2.37371  2.42895]
[-1.95666 -2.10862 -2.07589 ...  2.40223  2.35784  2.31777]
[ 0.

 79%|███████▉  | 476/604 [00:02<00:00, 166.32it/s]

[-1.03826 -0.95082 -0.93718 ...  1.24441  1.29917  1.33833]
[-1.04323 -1.07515 -1.09689 ...  0.81293  0.79994  0.79596]
[3.17708 3.15938 3.17263 ... 3.14532 3.16796 3.17251]
[-1.69659 -1.50594 -1.51392 ...  0.82599  0.85253  0.89763]
[ 3.1758   3.16788  3.109   ... -4.23956 -4.2497  -4.25929]
[-1.07152 -1.11096 -1.07914 ... -0.94849 -1.00334 -1.04929]
[-1.86394 -1.79508 -1.77793 ...  2.49673 -2.52297 -2.54373]
[ 3.75779  3.73785  3.71565 ... -4.71907 -4.72634 -4.74403]
[5.63226 5.62021 5.56984 ... 6.65051 6.65711 6.66341]
[-1.92759 -1.9824  -1.9338  ...  2.92661  2.92552  2.9201 ]
[ 3.12755  3.16649 -3.1462  ... -4.70925 -4.73337 -4.74356]
[ 3.22082  3.18996  3.18524 ... -4.07658 -4.05625 -4.04971]
[-3.92143 -3.95058 -3.96513 ... -3.74405 -3.71955 -3.6932 ]
[-1.13433 -1.20954 -1.13832 ...  1.62776  1.62637  1.62843]
[ 7.77175 -7.69901  7.6537  ...  9.27324  9.3053  -9.3157 ]
[ 2.83373  2.78356  2.77852 ... -2.51348 -2.48882 -2.46391]
[ 11.06385  11.03623  11.02363 ... -11.9996  -11.987

 85%|████████▍ | 511/604 [00:03<00:00, 167.13it/s]

[ 3.45543  3.39347  3.38713 ... -4.67479 -4.64109 -4.61026]
[5.2745  5.29756 5.25915 ... 6.79761 6.75285 6.71982]
[ 1.50981  1.51803  1.51307 ... -2.55608 -2.55147 -2.51339]
[-3.80266 -3.84007 -3.81419 ... -4.04769 -4.05903 -4.06554]
[-1.05087 -0.99939 -0.97375 ...  0.75094  0.73618  0.72524]
[-1.55497 -1.64735 -1.59641 ...  1.62111  1.59766  1.57658]
[-1.67082 -1.71803 -1.67401 ...  2.24507  2.28271  2.30322]
[-0.66319 -0.50378 -0.44286 ...  1.21541  1.0864   1.00619]
[-3.57108 -3.59199 -3.55336 ... -4.13695 -4.16907 -4.2099 ]
[-0.51167 -0.57611 -0.5601  ...  1.58579  1.59385  1.58225]
[-1.41421 -1.40784 -1.37982 ...  1.31207  1.29099  1.26495]
[-1.85177 -1.81542 -1.83912 ...  0.60633  0.60506  0.57321]
[-2.6464  -2.75918 -2.76813 ... -3.51588 -3.52828 -3.53066]
[ 8.2049   8.06284  8.06233 ... -9.56149 -9.55019 -9.5259 ]
[-4.36835 -4.43475 -4.37574 ... -5.43731 -5.50017 -5.54779]
[ 3.13315 -3.18329  3.17301 ...  2.67043  2.70548  2.72061]
[ 2.52744  2.50777  2.46976 ... -3.47637 -3.52

 87%|████████▋ | 528/604 [00:03<00:00, 165.83it/s]

[-2.53193 -2.50832 -2.48235 ... -3.54375 -3.52182 -3.51415]
[-3.19397 -3.40808 -3.29793 ... -5.23696 -5.23302 -5.22149]
[-1.74155 -1.77384 -1.79311 ...  2.38437  2.39198  2.37298]
[-1.59231 -1.57873 -1.51961 ...  1.2996   1.28362  1.24908]
[3.09645 3.20983 3.08394 ... 3.30351 3.30131 3.29307]
[ 3.64829  3.64857  3.58993 ... -5.02749 -5.05933 -5.07517]
[ 5.22178 -5.19786  5.14143 ...  5.6117   5.58991  5.5578 ]
[-2.00862 -1.97421 -1.98467 ...  1.12448  1.28229  1.45589]
[ 1.40582 -1.42327  1.37616 ...  2.87065  2.86194  2.84799]
[-1.45607 -1.48565 -1.54647 ... -1.94405 -1.88517 -1.82446]
[ 1.7956   1.80376  1.8011  ... -2.93991 -2.92475 -2.90533]
[6.52298 6.39867 6.35458 ... 7.85854 7.95446 8.02949]
[2.20542 2.14403 2.13929 ... 2.76638 2.75012 2.71882]
[-2.50568 -2.5116  -2.47506 ... -3.35259 -3.38905 -3.41552]
[ 2.84146  2.82314  2.79487 ... -4.15182 -4.20292 -4.23272]
[8.4496  8.28062 8.25708 ... 9.69097 9.69399 9.69186]
[ 4.38805  4.36534  4.35658 ... -5.73258 -5.71648 -5.66015]
[-1.

 96%|█████████▌| 579/604 [00:03<00:00, 165.87it/s]

[ 3.32342  3.27982  3.2715  ... -3.74224 -3.72752 -3.67153]
[-2.37417 -2.39414 -2.3635  ...  2.78765  2.77123  2.75612]
[-2.7176  -2.73598 -2.73951 ... -3.16026 -3.18348 -3.19236]
[-2.20941 -2.14701 -2.18028 ... -2.72185 -2.69783  2.67909]
[-4.64557 -4.59411 -4.57155 ... -5.44743 -5.51796 -5.56194]
[ 3.0026   3.00006  2.97662 ... -3.71635 -3.73953 -3.76304]
[-4.852   -4.69561 -4.72999 ...  4.76897  4.72995  4.70759]
[-0.78346 -0.87238 -0.85857 ...  1.51151  1.50619  1.52006]
[-4.98389 -4.79408 -4.8123  ...  5.12323  5.11364  5.10278]
[ 3.49443  3.51851  3.49853 ... -4.87825 -4.90932 -4.96617]
[ 2.90975  2.87117  2.85502 ... -3.84483 -3.83421 -3.81475]
[ 1.99604  1.99505  1.98255 ... -2.75858 -2.79196 -2.80994]
[-4.04756  4.03897  4.03113 ... -4.73598 -4.77978 -4.80838]
[-1.39928 -1.44441 -1.40775 ... -2.27859 -2.29135 -2.29717]
[-1.72706 -1.83496 -1.79312 ...  2.79945  2.78278  2.77045]
[10.64798 10.62413 10.55656 ... 12.36034 12.37167 12.37825]
[5.75031 5.72274 5.67483 ... 6.6837  6.7

100%|██████████| 604/604 [00:03<00:00, 164.54it/s]


[ 0.60383  0.53675 -0.5199  ...  1.31364  1.27585  1.24685]
[ 0.72947 -0.73623 -0.74896 ... -1.06163 -1.06431 -1.07587]
[-2.23003  2.12381 -2.14158 ... -1.30455 -1.42646 -1.5421 ]
[5.05685 4.95321 4.98668 ... 4.8377  4.8077  4.77883]
[1.57084 1.53246 1.55653 ... 1.56463 1.46057 1.36847]
[-3.03684 -3.09277 -3.06968 ... -3.67649 -3.63257 -3.59181]
[ 1.2962  -1.42688 -1.39066 ...  1.3405   1.33871  1.34885]
[-3.2015  -3.2223  -3.15923 ... -4.24142 -4.26006 -4.27711]
[-4.89375 -4.80843 -4.76985 ...  5.33879  5.32285  5.31658]
[ 4.88185 -4.82629 -4.82326 ...  4.23865  4.17794  4.12401]
[ 2.92428  2.88747  2.84916 ... -3.47967 -3.548   -3.60983]
[5.99699 5.95005 5.89447 ... 7.50106 7.56407 7.59221]
[ 2.99524  2.97762  2.95458 ... -3.4215  -3.46267 -3.50287]
[-1.5025  -1.48315 -1.4535  ...  1.9404   1.85635  1.77943]
[ 3.63353  3.67849  3.64284 ... -4.89766 -4.93629 -4.96709]
[ 6.39376 -6.31295  6.29634 ...  6.98245  6.97138  6.97556]
[-2.19584 -2.22411 -2.18671 ...  2.36483  2.33399  2.30662

  3%|▎         | 18/604 [00:00<00:03, 169.81it/s]

[2.43683 2.55261 2.45221 ... 3.7262  3.79042 3.82982]
[-3.91982 -3.95886 -3.91513 ... -4.98192 -5.00876 -5.02323]
[0.43276 0.48561 0.45942 ... 1.44998 1.43722 1.42806]
[-0.66551 -0.75154 -0.65921 ...  2.63257  2.63212  2.6147 ]
[1.963   2.0005  1.90072 ... 3.05936 3.1075  3.14985]
[ 0.48104  0.68115 -0.6458  ...  2.05605  2.12637  2.2358 ]
[-1.93962 -2.06044 -2.01327 ...  3.86651  3.89419  3.93651]
[-3.37986  3.36447  3.31073 ...  4.7155   4.76253  4.82713]
[-1.28512 -1.29525 -1.23775 ...  1.22484  1.26958  1.31713]
[1.80598 1.9524  1.90096 ... 1.68791 1.84335 2.11044]
[-0.91336 -1.00181 -0.90095 ...  2.16285  2.15002  2.10476]
[ 0.9556  -0.88763  0.93191 ...  2.03882  2.1048   2.18184]
[-0.53091 -0.51084 -0.51265 ...  1.41335  1.44397  1.46209]
[-0.49344 -0.48242 -0.44284 ...  0.83414  0.83143  0.83168]
[0.97131 0.95591 0.98673 ... 1.14412 1.29539 1.50075]
[-0.5266  -0.60384 -0.57844 ...  1.47529  1.39448  1.30782]
[0.18997 0.28135 0.27718 ... 0.6062  0.51436 0.47203]
[ 10.29604   9.9

  9%|▊         | 52/604 [00:00<00:03, 156.88it/s]

[0.80477 0.81308 0.79155 ... 1.26548 1.28131 1.25752]
[0.93617 1.02045 0.89986 ... 1.7283  1.74252 1.73776]
[-0.69559 -0.66632 -0.67544 ...  1.172    1.2134   1.23807]
[-1.91496 -2.06716 -2.01477 ...  3.7931   3.77117  3.77919]
[-1.59636 -1.65708 -1.64993 ...  2.46194  2.46375  2.45013]
[-2.24787 -2.22455 -2.19756 ...  2.85626  2.97069  3.10137]
[0.75353 0.79054 0.71172 ... 1.12273 1.24529 1.36096]
[-3.34723 -3.34311 -3.29344 ... -4.69371 -4.68106 -4.67414]
[1.07767 1.06581 1.05281 ... 0.64382 0.7131  0.76524]
[1.74525 1.76308 1.74085 ... 1.9454  1.94659 1.94443]
[-2.89332  2.87439  2.84271 ...  2.66465  2.63814  2.65319]
[-0.66654 -0.77074 -0.74021 ... -1.16418 -1.19723 -1.22534]
[-6.13499  6.09119  6.00998 ...  7.50654  7.67738  7.80092]
[-1.00795 -0.9766  -1.00969 ...  1.12026  1.16701  1.19269]
[-1.0307  -0.995   -1.01502 ...  0.45108  0.31855  0.20676]
[-3.03299 -3.06836 -2.9812  ...  3.05311  3.15423  3.24906]
[-1.96676 -2.0852  -2.03736 ... -2.8967  -2.91964 -2.93462]
[-0.36307 

 14%|█▍        | 86/604 [00:00<00:03, 161.54it/s]

[-3.19631 -3.19223 -3.15122 ... -3.76752 -3.76443 -3.77081]
[-2.15185 -2.14419 -2.13359 ... -1.9951  -2.04021 -2.09177]
[ 2.09409  2.13222  2.13269 ... -2.5802  -2.56917 -2.43317]
[ 0.37826  0.42822 -0.4849  ...  2.0161   2.00884  2.05373]
[-0.45205 -0.40842 -0.35827 ...  1.21472  1.20176  1.1576 ]
[0.90588 1.00489 0.94724 ... 2.51942 2.49075 2.43707]
[2.00379 2.14025 2.12332 ... 3.53877 3.46374 3.34876]
[ 2.32754  2.29267  2.21462 ... -3.54621 -3.88327 -4.16329]
[2.68297 2.74477 2.69855 ... 3.67913 3.78469 3.8777 ]
[-6.57495 -6.53106 -6.49076 ...  6.65799  6.78344  6.89296]
[-6.81919 -6.77705 -6.75762 ...  7.47013  7.54883  7.62658]
[1.76931 1.88922 1.86608 ... 2.82064 2.76711 2.72958]
[-0.99933 -1.02286 -0.98859 ...  1.3603   1.4136   1.47527]
[-2.15057 -2.2472  -2.23353 ...  1.70001  1.79664  1.88693]
[-1.12332  1.24611  1.23945 ...  1.41635  1.41171  1.39736]
[-0.50114 -0.49092 -0.41929 ... -1.62094 -1.62062 -1.63698]
[ 1.12752  1.2133   1.13185 ...  0.54306 -0.53317 -0.54504]
[-0.

 23%|██▎       | 137/604 [00:00<00:02, 166.05it/s]

[ 1.48513  1.4859   1.44886 ... -2.44976 -2.47827 -2.46239]
[5.17271 5.17273 5.09788 ... 6.13112 6.22932 6.3447 ]
[-1.19352 -1.13917 -1.09298 ...  2.20294  2.18106  2.13082]
[-8.07001 -8.04584 -7.96873 ...  8.05933  8.22832  8.38544]
[-1.28054 -1.28727 -1.25775 ...  0.58824  0.5765   0.60095]
[-0.33144 -0.4314  -0.44435 ...  1.21747  1.28427  1.35777]
[-2.95848 -3.0272  -2.99108 ... -3.33797 -3.39433 -3.45885]
[ 0.50879 -0.52152 -0.50049 ...  1.46273  1.42675  1.35256]
[-6.61637 -6.54548 -6.48285 ...  7.25023  7.36628  7.46602]
[-1.33763 -1.43227 -1.4239  ...  1.59764  1.62665  1.64383]
[1.88314 1.93348 1.93929 ... 1.92525 1.90309 1.8921 ]
[-0.7022  -0.71619 -0.71314 ... -0.2992  -0.2915  -0.28402]
[0.85544 0.93509 0.92104 ... 0.63483 0.55124 0.49619]
[-0.9788  -1.00015  0.96973 ...  2.17455  2.20782  2.21252]
[-2.11983 -2.09289 -2.09284 ...  2.02859  2.14457  2.22192]
[1.22277 1.45586 1.39438 ... 1.39359 1.18684 1.03846]
[-2.62202 -2.52207 -2.52704 ... -1.46189 -1.45908 -1.4605 ]
[3.3

 28%|██▊       | 171/604 [00:01<00:02, 165.87it/s]

[1.34434 1.33013 1.3311  ... 1.38742 1.45123 1.4654 ]
[-3.99186 -3.9352  -3.90854 ...  4.25058  4.29654  4.39755]
[0.42314 0.52499 0.54517 ... 1.32803 1.29944 1.31333]
[1.38726 1.36857 1.3513  ... 1.78895 1.83687 1.88054]
[ 1.46526 -1.45102 -1.46732 ...  1.55384  1.66002  1.73295]
[-0.63395  0.68124 -0.63842 ... -1.73381 -1.68608 -1.63256]
[2.04776 2.00488 1.9934  ... 1.84465 1.90204 1.97581]
[ 2.74324  2.78781  2.76036 ... -3.43826 -3.39952 -3.35757]
[0.95023 0.95642 0.98671 ... 2.2658  2.18383 2.07431]
[1.13504 1.1766  1.11975 ... 3.06882 3.13222 3.14393]
[-4.23612 -4.22934 -4.17301 ...  5.66034  5.66852  5.66463]
[-1.92469 -1.93709 -1.9186  ...  2.74578  2.8698   2.99523]
[1.41982 1.54785 1.51862 ... 3.60243 3.42723 3.27388]
[-2.42708 -2.42845 -2.40954 ...  2.29249 -2.33078 -2.37996]
[1.4111  1.48309 1.42356 ... 3.17721 3.07226 2.96295]
[-3.44273 -3.42088 -3.48939 ...  1.84864  1.83317  1.85247]
[0.73809 0.66665 0.65048 ... 1.19398 1.31373 1.37758]
[-1.66616 -1.70676 -1.68564 ...  2

 34%|███▍      | 205/604 [00:01<00:02, 164.43it/s]

[-0.92451 -0.87006 -0.85798 ... -1.34329 -1.57608 -1.95423]
[-1.8769  -1.94586 -1.8975  ... -3.52815 -3.58701 -3.67376]
[-1.06708 -1.10116 -1.09093 ... -1.49472 -1.51488  1.54831]
[-6.17142 -6.1927  -6.12863 ...  7.08442  7.13094  7.14919]
[-1.3556  -1.39183 -1.3826  ...  2.02052  2.06196  2.10668]
[-1.11919 -1.0853  -1.06963 ... -0.20647 -0.20776 -0.30543]
[-1.27194 -1.25077 -1.26418 ... -1.69625 -1.76319 -1.81447]
[-1.22693 -1.2834  -1.24426 ...  2.87557  2.88178  2.843  ]
[ 2.50701  2.48011  2.42089 ... -2.47462 -2.51089 -2.52365]
[ 1.79359  1.97789  1.88181 ... -4.72832 -4.74006 -4.75837]
[1.1666  1.28411 1.27334 ... 1.02416 1.10211 1.24352]
[1.94277 2.11184 2.08104 ... 3.62265 3.63469 3.61105]
[1.75056 1.6444  1.64425 ... 1.58495 1.61112 1.64116]
[2.18034 2.24942 2.18249 ... 3.50833 3.58084 3.72827]
[-1.46791 -1.51094 -1.50715 ...  2.25295  2.30277  2.33083]
[-1.28108 -1.32458 -1.29664 ...  2.0114   1.98081  1.91848]
[ 6.4862   6.48817  6.38276 ... -7.94679 -8.05844 -8.16561]
[-6.

 37%|███▋      | 222/604 [00:01<00:02, 165.10it/s]

[-0.85876 -0.82124 -0.77208 ... -0.82149 -0.82269 -0.80997]
[-2.75767 -2.81207 -2.7787  ... -3.97168 -3.97711 -3.97652]
[1.13871 1.11647 1.13395 ... 1.25489 1.2094  1.17002]
[-2.91839 -2.8941  -2.84421 ... -4.14803 -4.14981 -4.14595]
[-1.61861 -1.60508 -1.57444 ... -2.86048 -2.93274 -2.98086]
[-1.25325 -1.29482 -1.22822 ...  1.45715  1.47188  1.48126]
[-6.37146 -6.36065 -6.31794 ...  6.87235  6.96574  7.08266]
[-3.42272 -3.45357 -3.40525 ... -4.09443 -4.14229 -4.21202]
[-3.07963 -3.08018 -3.06287 ...  2.70112  2.72441  2.73603]
[-3.11254 -3.31141 -3.2752  ...  5.16443  5.11242  5.07269]
[-2.27242 -2.3011  -2.2733  ...  1.64304  1.60231  1.55398]
[2.86433 3.01547 2.94962 ... 5.36508 5.43138 5.45988]
[-2.31063 -2.27814 -2.24906 ... -2.94123 -2.92391 -2.89083]
[2.1148  2.14759 2.07928 ... 1.82314 1.79154 1.70412]
[ 4.43045  4.49832  4.49666 ... -5.15056 -5.22271 -5.31502]
[-0.60862 -0.73056 -0.69489 ... -0.87463 -0.82159 -0.77828]
[-1.66576 -1.70356 -1.68961 ...  2.54826  2.65885  2.71481

 42%|████▏     | 256/604 [00:01<00:02, 165.90it/s]

[-1.74648 -1.76714 -1.68686 ... -2.51379 -2.60162 -2.65267]
[-1.06763 -1.09593 -1.04688 ... -2.0598  -2.02763 -1.99864]
[0.82452 0.78115 0.75047 ... 0.80886 0.83832 0.84937]
[ 0.98499  1.03288  1.02408 ... -1.7997  -1.79126 -1.78214]
[5.65023 5.6127  5.52931 ... 7.33404 7.41213 7.45954]
[2.22524 2.26969 2.23916 ... 1.31753 1.33612 1.35554]
[-2.3637  -2.38535 -2.34565 ... -2.78347 -2.82867 -2.87032]
[-7.44935 -7.45061 -7.36076 ...  8.80171  8.74043  8.71808]
[-1.31227 -1.28489 -1.28737 ...  1.50944 -1.48256 -1.46055]
[-1.45253 -1.53496 -1.52028 ... -2.57067 -2.58102 -2.5784 ]
[-1.66434 -1.67382 -1.66452 ...  0.48202  0.43719  0.43936]
[ 2.92615  2.92013  2.92647 ... -3.11107 -3.15731 -3.16915]
[0.94471 0.87814 0.82657 ... 1.18893 1.24104 1.28569]
[7.72428 7.66211 7.59341 ... 9.61749 9.78366 9.91366]
[1.82673 1.84729 1.84552 ... 2.19127 2.1976  2.20288]
[-3.89646 -3.87272 -3.88818 ...  3.38698  3.43161  3.46726]
[ 3.60427  3.66088  3.63623 ... -4.72473 -4.72558 -4.73999]
[-1.1987  -1.231

 48%|████▊     | 290/604 [00:01<00:01, 164.07it/s]

[ 0.43726  0.54603 -0.47145 ... -1.86473 -1.87367 -1.88736]
[2.11867 2.14796 2.15592 ... 1.84918 1.86433 1.88644]
[ 8.40753  8.2675   8.15778 ...  9.89008 10.04076 10.18375]
[ 8.54137  8.38641  8.33197 ... -8.18777 -8.25687  8.33854]
[7.40722 7.35894 7.27271 ... 8.20005 8.27594 8.34266]
[-3.40194 -3.45008 -3.3992  ... -4.38744 -4.39079 -4.3881 ]
[ 6.29925  6.42873  6.39899 ... -7.58774 -7.60238 -7.61421]
[1.11145 1.38032 1.28035 ... 1.86761 1.87426 1.86937]
[-1.67643 -1.61316 -1.62436 ... -1.6249  -1.5554  -1.49706]
[-1.21698 -1.22883 -1.2288  ...  2.16992  2.17894 -2.19696]
[ 0.57312 -0.55139 -0.59392 ...  1.34782  1.31946  1.36525]
[-2.65821  2.68377  2.65657 ...  3.55361 -3.60446 -3.65116]
[-2.56516 -2.55737  2.52457 ... -3.15419 -3.19296 -3.21928]
[-0.54816 -0.65835 -0.63324 ...  1.15622  1.13383  1.1373 ]
[ 2.28556  2.31839  2.2848  ... -2.78654 -2.8163  -2.84412]
[-0.76365 -0.54312 -0.69371 ...  0.40933  0.34476  0.27157]
[ 1.2393   1.25232 -1.28392 ... -1.00339 -1.01396 -1.03317

 54%|█████▎    | 324/604 [00:01<00:01, 165.39it/s]

[ 10.52912  10.36428  10.29133 ... -10.55706 -10.68746 -10.80441]
[-0.74329 -0.78561 -0.76189 ...  1.75546  1.72551  1.64211]
[-1.53135 -1.56774 -1.52552 ...  2.48147  2.50602  2.52102]
[ 3.18917  3.19266  3.15501 ... -4.66504 -4.65448 -4.64288]
[-3.58677  3.64016  3.60268 ... -4.12759 -4.18421 -4.22361]
[8.08914 8.03917 7.91522 ... 9.3677  9.4777  9.56449]
[ 1.29523 -1.22883  1.22425 ...  1.54879  1.64513  1.76017]
[-2.1867  -2.2365  -2.21894 ...  2.95243  2.9572   2.92809]
[ 2.88888  2.93786  2.89438 ... -3.35183 -3.38491 -3.42234]
[-1.14887 -1.09018 -1.08319 ... -0.8684  -0.8589  -0.87689]
[-1.42013 -1.44437 -1.39914 ...  1.47922  1.47729  1.47879]
[-0.91742  0.9887  -0.96924 ...  1.1993   1.10429  1.04604]
[-0.83797 -0.82412 -0.82341 ... -0.8845  -0.89868 -0.91014]
[-2.1837  -2.18353 -2.14197 ... -3.24872 -3.2663  -3.29101]
[ 7.99429  7.90486  7.78195 ... -9.844   -9.90077 -9.95676]
[-10.0145    9.92147   9.84314 ...  10.634    10.73074  10.81343]
[ 2.58329  2.56145  2.48758 ... -2

 62%|██████▏   | 375/604 [00:02<00:01, 167.01it/s]

[-2.58482 -2.55025 -2.51215 ... -2.35791 -2.30373 -2.26386]
[-2.18209 -2.23579 -2.20565 ...  2.63909  2.69444 -2.71855]
[-9.22697 -9.14748 -9.06831 ... 10.28846 10.39327 10.47304]
[3.39856 3.36137 3.30922 ... 3.88704 3.93776 3.97341]
[-1.94811 -2.00043 -1.94579 ...  1.85847 -1.93346 -2.01667]
[ 2.9145   2.93849  2.89304 ... -3.84959 -3.89309 -3.92621]
[-2.05662  1.99008  1.99421 ...  1.6337   1.59449  1.56567]
[ 2.3877   2.41178  2.36615 ... -3.49939 -3.55953 -3.61621]
[-1.4811  -1.52458 -1.48556 ...  1.94349  1.95584  1.99897]
[-1.85119 -1.85714 -1.80988 ... -2.51213  2.53363  2.56758]
[-0.89827 -1.07598 -1.07999 ...  1.2368   1.16357  1.08832]
[-4.77254 -4.82306 -4.80842 ... -5.04836 -5.07745 -5.09935]
[-0.56376 -0.56026 -0.53963 ... -1.4096  -1.36154 -1.34223]
[-2.36192 -2.37549 -2.35318 ... -2.97456 -3.00521 -2.99665]
[-1.02278 -1.03632 -1.02044 ... -1.64321 -1.6655  -1.61344]
[ 3.37525  3.43471 -3.39857 ... -3.90828 -3.97387 -4.02758]
[-1.49225 -1.46964 -1.47449 ...  1.10785  1.14

 68%|██████▊   | 409/604 [00:02<00:01, 167.33it/s]

[1.6596  1.65489 1.63959 ... 2.01267 1.90692 1.80391]
[-2.29144 -2.26834 -2.25868 ... -2.0697  -2.09383 -2.11659]
[ 1.54326  1.65598  1.63949 ... -3.38753 -3.39156 -3.4074 ]
[ 1.82128 -1.84552 -1.85021 ... -1.56088 -1.53502 -1.52094]
[ 1.97732 -2.0256  -2.02031 ... -2.12082 -2.16399 -2.1194 ]
[-1.6381  -1.64738 -1.62956 ... -1.65585 -1.6787  -1.71707]
[-3.17244 -3.3002  -3.22939 ... -4.14192 -4.16978 -4.20267]
[-0.96619 -1.0395  -1.04295 ... -1.60748 -1.62028 -1.63702]
[-2.34454 -2.41373 -2.35868 ...  3.25513  3.26421  3.26744]
[ 2.41297  2.39042  2.29151 ... -2.28617 -2.38981 -2.50689]
[-2.49805 -2.50528 -2.46713 ... -2.99501 -3.01598 -3.04211]
[-1.31796 -1.3588  -1.39858 ...  1.9189   1.89851  1.88122]
[-2.25975 -2.2801  -2.23611 ... -2.64627 -2.68677 -2.7225 ]
[ 2.24367  2.23847  2.20837 ... -2.61958 -2.67373 -2.72116]
[1.4147  1.39403 1.31943 ... 0.98886 0.95137 0.96875]
[ 3.41584  3.41031  3.34794 ... -4.37687 -4.42527 -4.47782]
[0.42429 0.42079 0.40883 ... 0.99875 0.91865 0.83172

 73%|███████▎  | 443/604 [00:02<00:00, 167.48it/s]

[0.60032 0.53008 0.47545 ... 1.25253 1.26598 1.2345 ]
[-2.92817 -2.91304 -2.86879 ... -3.4119  -3.43376 -3.45894]
[2.23282 2.21229 2.19744 ... 2.84646 2.84993 2.815  ]
[ 2.64628  2.69876  2.67693 ... -3.36991 -3.3772  -3.36407]
[-1.68909 -1.66259 -1.67173 ...  2.25765  2.2976   2.36337]
[ 2.95478  2.96018  2.93012 ...  3.54347  3.56813 -3.58749]
[-0.19474 -0.2338  -0.22961 ... -1.44362 -1.4795  -1.5103 ]
[0.73852 0.84282 0.83387 ... 2.83137 2.80595 2.77186]
[2.84633 2.81833 2.79582 ... 2.67014 2.83328 2.99812]
[ 1.12899 -1.17999 -1.13561 ...  1.56227  1.58435  1.60759]
[-7.88753 -7.75863 -7.72063 ...  7.75469  7.78991  7.83103]
[0.50805 0.58449 0.55317 ... 1.16457 1.0935  0.9978 ]
[2.80033 2.78002 2.83754 ... 0.76243 0.77334 0.81246]
[ 2.26148  2.24457  2.2611  ... -3.09042 -3.10958 -3.11493]
[2.56349 2.5564  2.57439 ... 3.35986 3.36882 3.33192]
[ 2.05207  1.9345   2.00442 ... -2.16551 -2.16563 -2.16975]
[-2.45735 -2.483   -2.45653 ... -3.12754 -3.14848 -3.14658]
[-1.90354 -1.8404  -1.

 76%|███████▌  | 460/604 [00:02<00:00, 167.24it/s]

[-0.64002 -0.71298 -0.72397 ...  1.7542   1.67984  1.56543]
[ 1.47279  1.56814  1.48658 ... -2.91097 -2.96189 -2.98815]
[-2.0395  -2.05043 -2.04917 ...  2.64055  2.63903  2.6256 ]
[ 1.2387   1.26725  1.26431 ...  1.15674 -1.16524 -1.18394]
[ 3.15326  3.13158  3.1274  ... -2.13537 -2.16559 -2.19761]
[-0.88622 -0.86753 -0.89015 ... -1.6665  -1.76461 -1.82255]
[ 2.61263  2.61999  2.59177 ... -3.10051 -3.20141 -3.30345]
[-2.41441 -2.45646 -2.41284 ... -2.62737 -2.64265 -2.66887]
[ 3.06727  3.16727  3.07726 ...  3.549    3.60123 -3.58404]
[ 2.08568  2.07319  2.05169 ... -2.91623 -2.93981 -2.96275]
[-3.1134  -3.12733  3.08591 ... -3.4567  -3.47294 -3.49521]
[-1.75545 -1.74838 -1.73565 ...  1.70544  1.77402  1.84796]
[-2.48638 -2.64827 -2.61103 ...  2.56487  2.56594  2.54919]
[-3.24034 -3.14484 -3.13196 ...  3.61492  3.69147  3.72073]
[ 2.17662  2.10878  2.14415 ... -2.04425 -2.01366 -1.98572]
[ 11.37961  11.31175  11.20914 ... -12.35442 -12.44541 -12.54649]
[ 9.58897  9.48528  9.40392 ... 10

 85%|████████▍ | 512/604 [00:03<00:00, 168.18it/s]

[-2.21529 -2.18183 -2.11692 ... -2.65492 -2.76874 -2.91904]
[ 3.10956  3.07448  3.06398 ... -3.57455 -3.59382 -3.62651]
[ 1.00293  0.935   -0.93097 ... -1.73254 -1.71526 -1.69807]
[-1.6817  -1.6499  -1.65747 ...  1.57417  1.62095  1.65857]
[-2.8399  -2.8599  -2.85142 ... -2.84508 -2.86071 -2.87388]
[-1.41576 -1.39598 -1.37962 ...  1.86229  1.87905  1.89511]
[1.731   1.74581 1.64149 ... 2.32388 2.32039 2.3339 ]
[-1.93191 -1.93456 -1.94675 ...  2.096    2.13773  2.17089]
[ 1.61768  1.6404   1.63759 ... -1.12252 -1.09365 -1.09862]
[ 5.51714 -5.52238 -5.44586 ... -6.64094  6.72891  6.8077 ]
[8.97936 8.89841 8.83267 ... 9.70115 9.78501 9.85419]
[-2.55856 -2.58348 -2.62971 ...  1.50786  1.52656  1.55119]
[-3.90163 -3.92485 -3.87063 ... -5.74444 -5.7498  -5.75542]
[7.82162 7.79263 7.71206 ... 8.4158  8.51001 8.59363]
[-2.75532 -2.79411 -2.7689  ... -2.9199  -2.99888  3.06314]
[ 0.7002   0.65371  0.65865 ... -2.02894 -1.91309 -1.81634]
[-2.07577 -2.01405 -2.02049 ...  2.53256  2.58472  2.60428

 90%|█████████ | 546/604 [00:03<00:00, 166.57it/s]

[ -9.28284  -9.19498  -9.11037 ... -10.57003 -10.66709 -10.73513]
[ 2.19699 -2.21093  2.20493 ...  2.29415  2.25694  2.22611]
[-2.32797 -2.32565 -2.2894  ... -3.459   -3.52176 -3.57248]
[-2.27153 -2.46002 -2.34018 ...  5.08763  5.06703  5.03913]
[ 1.51044  1.49662  1.48626 ... -1.98605 -2.01829 -2.04816]
[ 5.72345  5.6642   5.59309 ... -6.49923 -6.55967 -6.64177]
[-1.74007 -1.79721 -1.78655 ...  2.43687  2.4322   2.42603]
[2.28384 2.27276 2.26369 ... 1.75765 1.77911 1.80685]
[ 1.42181  1.46617 -1.44116 ...  1.97292  1.94377 -1.92773]
[0.84154 0.92945 0.90175 ... 0.71623 0.81389 0.83559]
[-1.87133 -1.85166 -1.84953 ...  1.57247  1.61471  1.6613 ]
[0.94468 1.0571  1.00025 ... 2.83499 2.87453 2.90358]
[-1.32956 -1.25813 -1.27517 ...  1.04567  1.01159  0.99584]
[1.61756 1.62959 1.63195 ... 1.8673  1.81286 1.7687 ]
[3.72905 3.63079 3.60194 ... 3.96093 4.04586 4.09439]
[ 1.80024 -1.81255 -1.82    ...  1.09174  1.18411  1.27255]
[ 1.74063  1.75023  1.74644 ... -1.75821 -1.79496 -1.84345]
[-0.

 93%|█████████▎| 563/604 [00:03<00:00, 164.71it/s]

[1.03048 1.01335 1.00358 ... 1.52053 1.56632 1.54936]
[-2.78362 -2.79544 -2.76705 ... -3.25591 -3.35141 -3.54206]
[1.65713 1.69267 1.6452  ... 1.00602 0.97204 0.93355]
[0.73967 0.77389 0.77991 ... 1.2236  1.22488 1.24068]
[1.95708 1.97789 1.9475  ... 2.56359 2.61044 2.64538]
[0.63382 0.56974 0.61248 ... 1.25284 1.25305 1.23827]
[0.25286 0.39946 0.20759 ... 1.58403 1.55811 1.5201 ]
[ 1.72007  1.73026  1.685   ... -3.34301 -3.39603 -3.43791]
[ 2.04322  2.10747  2.07294 ... -3.89285 -3.82862 -3.73502]
[-2.90969 -2.92725 -2.85379 ... -4.32854 -4.33999 -4.33558]
[ 2.03962  2.06698  2.08121 ... -2.29775 -2.33098 -2.3693 ]
[-3.10026 -3.10316 -3.0651  ... -3.986   -3.93316 -3.88747]
[2.21947 2.29888 2.26214 ... 3.42311 3.36888 3.32585]
[-1.96218 -2.00216 -1.98842 ...  2.00598  2.05461  2.08615]
[ 9.51529  9.50565  9.39406 ... 11.53954 11.66264 11.76478]
[-5.14294 -5.06157 -5.00569 ...  4.95138  5.03884  5.12608]
[-1.51516 -1.49856 -1.49831 ...  1.2371  -1.2482  -1.26865]
[0.52037 0.65053 0.557

100%|██████████| 604/604 [00:03<00:00, 165.39it/s]

[ 2.28659 -2.33518 -2.3044  ... -3.03131 -3.03051 -3.0307 ]
[-1.0922  -1.00572 -1.06188 ... -1.20526 -1.21815 -1.23401]
[-6.67743 -6.60241 -6.55882 ...  7.05521  7.08709  7.10526]
[-0.47998 -0.47442 -0.4439  ...  1.26674  1.26588  1.26531]
[ 4.82649  4.72311  4.63249 ... -5.18269 -5.27353 -5.36503]
[-1.24939 -1.21395 -1.2442  ... -1.24602 -1.20815 -1.15266]
[-2.631   -2.71398 -2.67186 ...  3.32173  3.35439  3.39402]
[ 4.70844  4.68619  4.65344 ... -3.24487 -3.33232 -3.42144]
[-2.63095 -2.66354 -2.64382 ... -2.98912 -3.02896 -3.06745]
[1.93929 1.93893 1.91624 ... 2.03405 2.10318 2.16784]
[ 2.58515  2.57667 -2.55275 ... -2.83692 -2.85545 -2.87454]
[ 2.18771  2.22161  2.1972  ... -2.98655 -3.02188  3.0524 ]
[-7.96535 -7.87855 -7.82128 ...  8.26363  8.33934  8.38976]
[-1.81424 -1.82038 -1.81349 ...  2.3795   2.37952  2.3824 ]
[ 3.05729  3.12763 -3.07787 ... -3.71729 -3.7358  -3.75339]
[ 3.8162   3.81145  3.72062 ... -5.2492  -5.32383 -5.37336]
[ 2.2177   2.20772  2.19562 ... -2.43888 -2.49

In [12]:
print(WJ_deform.keys())

dict_keys(['360002', '360003', '360004', '360006', '360007', '360008', '360009', '360013', '360015', '360017', '360020', '360021', '360022', '360023', '360026', '360029', '360030', '360031', '360032', '360034', '360036', '360038', '360040', '360041', '360042', '360043', '360045', '360048', '360051', '360052', '360055', '360056', '360058', '360059', '360061', '360063', '360066', '360067', '360069', '360070', '360072', '360074', '360076', '360079', '360081', '360082', '360083', '360085', '360086', '360087', '360089', '360091', '360092', '360097', '360100', '360102', '360104', '360106', '360107', '360108', '360109', '360110', '360111', '360114', '360118', '360119', '360125', '360126', '360127', '360128', '360132', '360136', '360137', '360138', '360139', '360140', '360141', '360144', '360145', '360146', '360150', '360151', '360152', '360155', '360158', '360160', '360161', '360162', '360166', '360167', '360168', '360169', '360172', '360173', '360176', '360178', '360179', '360181', '360182',

In [11]:
print(len(WJ_deform['LBC360277']),WJ_deform['LBC360277'][0],WJ_deform['LBC360277'][-1])


4002 0.40068 0.23097


In [33]:

for key in WJ_deform.keys():
    if not key in past_excel.keys():
        print(key)
        not_in.append(key)
for key in past_excel.keys():
    if not key in WJ_deform.keys():
        print(key)

LBC360043
LBC360070
LBC360082
LBC360086
LBC360109
LBC360161
LBC360183
LBC360185
LBC360217
LBC360224
LBC360237
LBC360268
LBC360282
LBC360286
LBC360334
LBC360352
LBC360375
LBC360378
LBC360386
LBC360418
LBC360434
LBC360458
LBC360482
LBC360487
LBC360494
LBC360511
LBC360560
LBC360612
LBC360629
LBC360719
LBC360726
LBC360746
LBC360786
LBC360804
LBC360807
LBC360809
LBC360845
LBC360866
LBC360895
LBC360911
LBC361015
LBC361079
LBC361107
LBC361138
LBC361156
LBC361203
LBC361221
LBC361229
LBC361284
LBC361307
LBC


In [7]:
# Open the file in read mode
with open(r'C:\Users\v1wpark\Documents\Projects\lv-parametric-modelling\ipynb\edinburgh\ordered_LocalDeformity_newtemp_synthseg_R.txt', 'r') as file:
    content = file.read()

# Replace 'L' with 'R'
new_content = content.replace('L', 'R')

# Open the file in write mode and save the modified content
with open(r'C:\Users\v1wpark\Documents\Projects\lv-parametric-modelling\ipynb\edinburgh\ordered_LocalDeformity_newtemp_synthseg_R.txt', 'w') as file:
    file.write(new_content)

print("All 'L' characters have been replaced with 'R'.")

All 'L' characters have been replaced with 'R'.


In [42]:
new_L = o3d.io.read_triangle_mesh(rf"C:\Users\v1wpark\Documents\Projects\lv-parametric-modelling\ipynb\edinburgh\edinburgh\avg_mesh\{mode}.obj")
o3d.visualization.draw_geometries([new_L,jerry_L])

In [43]:
import open3d as o3d
import util
import copy
jerry_L = o3d.io.read_triangle_mesh(r"D:\NextCloud\원정\2024\Data-to-KAIST\Task1) cross-hippo\edinburgh\avg_mesh\ordered_new_temp_mesh_L_2001.obj")
jerry_org =copy.deepcopy(jerry_L)
mode="manual_l_old_avg"
new_L = o3d.io.read_triangle_mesh(rf"D:\IdeaProjects\IITP_synth\lv-parametric-modelling\ipynb\edinburgh_longi_hippo\l_avg.obj")
new_vert= np.asarray(new_L.vertices)
jerry_vert= np.asarray(jerry_L.vertices)
for i in range(3):
    new_vert[:,i]=new_vert[:,i]-np.min(new_vert[:,i])+np.min(jerry_vert[:,i])
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()

mesh.scale(100, center=mesh.get_center())
coord_vert = np.asarray(mesh.vertices)
for i in range(3):
    coord_vert[:, i] =coord_vert[:, i] +np.min(jerry_vert[:,i])
L_temp_mesh_r = copy.deepcopy(new_L)
R = mesh.get_rotation_matrix_from_xyz((-np.pi*6/5, 0,0))
L_temp_mesh_r.rotate(R, center=(0, 0, 0))

vert = np.asarray(L_temp_mesh_r.vertices)
vert[:,0] *=-1

R = mesh.get_rotation_matrix_from_xyz((0, np.pi,0))
L_temp_mesh_r.rotate(R, center=(0, 0, 0))

tri = np.asarray(L_temp_mesh_r.triangles)
tri0 = tri.copy()
tri[:,0]=tri0[:,2]
tri[:,2]=tri0[:,0]


# R = mesh.get_rotation_matrix_from_xyz((np.pi+0.5,np.pi, 0))
# L_temp_mesh_r.rotate(R, center=mesh.get_center())
trans_vert=np.asarray(L_temp_mesh_r.vertices)

for i in range(3):
    trans_vert[:,i]=trans_vert[:,i]-np.min(trans_vert[:,i])+np.min(jerry_vert[:,i])
o3d.visualization.draw_geometries([L_temp_mesh_r,jerry_L,mesh])

L_temp_mesh_r.compute_vertex_normals()
trans_pcd = o3d.geometry.PointCloud(points=o3d.utility.Vector3dVector(trans_vert))
trans_pcd.normals = o3d.utility.Vector3dVector(np.asarray(L_temp_mesh_r.vertex_normals))

jerry_pcd = o3d.geometry.PointCloud(points=o3d.utility.Vector3dVector(jerry_vert))
jerry_L.compute_vertex_normals()
jerry_pcd.normals = o3d.utility.Vector3dVector(np.asarray(jerry_L.vertex_normals))

util.regist_mesh_pcd(trans_pcd, jerry_pcd, L_temp_mesh_r)
o3d.visualization.draw_geometries([jerry_L,L_temp_mesh_r])
o3d.io.write_triangle_mesh(rf"D:\IdeaProjects\IITP_synth\lv-parametric-modelling\ipynb\edinburgh_longi_hippo\ordered_l.obj",L_temp_mesh_r)

[Open3D WARNING] Write OBJ can not include triangle normals.


True

In [75]:
import os 
obj_list= os.listdir(r"W:\Wonjung_Park_July_Aug_2024\Deformity\scan1\ordered\avg_meshes\new_avg_standard")
meshes = []
for obj in obj_list:
    if "formed" in obj:
        print(obj)
        mesh = o3d.io.read_triangle_mesh(rf"W:\Wonjung_Park_July_Aug_2024\Deformity\scan1\ordered\avg_meshes\new_avg_standard\{obj}")
        meshes.append(mesh)
o3d.visualization.draw_geometries(meshes)

formed-ordered_manual_l_old_4002_avg.obj
formed-ordered_manual_r_old_4002_avg.obj
formed-ordered_synthseg_l_new_2001_avg.obj
formed-ordered_synthseg_l_new_4002_avg.obj
formed-ordered_synthseg_l_old_4002_avg.obj
formed-ordered_synthseg_r_new_2001_avg.obj
formed-ordered_synthseg_r_new_4002_avg.obj
formed-ordered_synthseg_r_old_4002_avg.obj


In [53]:
with open(rf'D:\Data-to-KAIST\Task1) cross-hippo\edinburgh\avg_mesh\old_temp_mesh_L.obj', 'r') as file:
	lines = file.readlines()

# Open a new file to write the modified content
with open(rf'D:\Data-to-KAIST\Task1) cross-hippo\edinburgh\avg_mesh\formed-old_temp_l_avg.obj', 'w') as file:
	for line in lines:
		# Skip lines starting with 'vn'
		if line.startswith('vn'):
			continue
		if line.startswith('#'):
			continue
		# Modify lines starting with 'v'
		if line.startswith('v'):
			parts = line.split()
			new_parts = parts[:4]  # Keep only the first 4 elements (v and the first three numbers)
			line = ' '.join(new_parts) + '\n'
		# Modify lines starting with 'f'
		if line.startswith('f'):
			parts = line.split()
			new_parts = [parts[0]] + [part.split('//')[0] for part in parts[1:]]
			line = ' '.join(new_parts) + '\n'
		file.write(line)

print("File has been processed and saved as 'yourfile_modified.txt'.")
# Open the original file in read mode

File has been processed and saved as 'yourfile_modified.txt'.


In [17]:
# Open the original file in read mode
mode ="manual_r_avg"
modes = os.listdir(rf"W:\Wonjung_Park_July_Aug_2024\Deformity\scan1\ordered\avg_meshes\new_avg_standard")
for mode in modes:
    if 'obj' in mode:
        with open(rf'W:\Wonjung_Park_July_Aug_2024\Deformity\scan1\ordered\avg_meshes\new_avg_standard\{mode}', 'r') as file:
            lines = file.readlines()

        # Open a new file to write the modified content
        with open(rf'W:\Wonjung_Park_July_Aug_2024\Deformity\scan1\ordered\avg_meshes\new_avg_standard\formed-{mode}', 'w') as file:
            for line in lines:
                # Skip lines starting with 'vn'
                if line.startswith('vn'):
                    continue
                if line.startswith('#'):
                    continue
                # Modify lines starting with 'v'
                if line.startswith('v'):
                    parts = line.split()
                    new_parts = parts[:4]  # Keep only the first 4 elements (v and the first three numbers)
                    line = ' '.join(new_parts) + '\n'
                # Modify lines starting with 'f'
                if line.startswith('f'):
                    parts = line.split()
                    new_parts = [parts[0]] + [part.split('//')[0] for part in parts[1:]]
                    line = ' '.join(new_parts) + '\n'
                file.write(line)

        print("File has been processed and saved as 'yourfile_modified.txt'.")
        # Open the original file in read mode


File has been processed and saved as 'yourfile_modified.txt'.
File has been processed and saved as 'yourfile_modified.txt'.
File has been processed and saved as 'yourfile_modified.txt'.
File has been processed and saved as 'yourfile_modified.txt'.
File has been processed and saved as 'yourfile_modified.txt'.
File has been processed and saved as 'yourfile_modified.txt'.
File has been processed and saved as 'yourfile_modified.txt'.
File has been processed and saved as 'yourfile_modified.txt'.
File has been processed and saved as 'yourfile_modified.txt'.
File has been processed and saved as 'yourfile_modified.txt'.


In [52]:
import open3d as o3d
import numpy as np
R_temp_mesh = o3d.io.read_triangle_mesh(r"W:\Wonjung_Park_July_Aug_2024\Deformity\scan1\ordered\avg_meshes\jerry_average_hippo_r_old_4002.obj")
print(np.asarray(R_temp_mesh.vertices).shape)
o3d.visualization.draw_geometries([R_temp_mesh])

(4002, 3)


In [53]:
vert_r = np.asarray(R_temp_mesh.vertices)
print(np.max(vert_r,axis=0),np.min(vert_r,axis=0))
for i in range(3):
    vert_r[:,i]-=vert_r[:,i].min()

[-139.99200439  -94.3884964  -114.70600128] [-166.26300049 -136.15800476 -145.2769928 ]


In [54]:
R_temp_mesh_old = o3d.io.read_triangle_mesh(r"C:\Users\v1wpark\Documents\Projects\lv-parametric-modelling\ipynb\edinburgh\edinburgh\avg_mesh\synthseg_r_avg.obj")


In [55]:
R_temp_mesh_old.paint_uniform_color([0.5, 0.5, 0.5])
o3d.visualization.draw_geometries([R_temp_mesh_old,R_temp_mesh])

In [65]:
meshes =[]
import glob
meshfiles = glob.glob(r".\edinburgh\avg_mesh\*.obj")
for index, meshfile in enumerate(meshfiles):
    try:
        mesh = o3d.io.read_triangle_mesh(meshfile)
        mesh_v = np.asarray(mesh.vertices)
        mesh_v[:,0] +=30*index
        meshes.append(mesh)
    except:
        continue
o3d.visualization.draw_geometries(meshes)    

In [60]:
import util
coord=o3d.geometry.TriangleMesh.create_coordinate_frame()
coord.scale(10, center= coord.get_center())


R = mesh.get_rotation_matrix_from_xyz((np.pi,np.pi,0))
R_temp_mesh_old.rotate(R, center=(0, 0, 0))
R_temp_mesh_old.compute_vertex_normals()
r_jerry_pcd = o3d.geometry.PointCloud(points=o3d.utility.Vector3dVector(vert_r))
r_jerry_pcd.normals= o3d.utility.Vector3dVector(np.asarray(R_temp_mesh_old.vertex_normals))
temp_pcd =o3d.geometry.PointCloud(points=o3d.utility.Vector3dVector(np.asarray(R_temp_mesh.vertices)))
R_temp_mesh.compute_vertex_normals()
temp_pcd.normals= o3d.utility.Vector3dVector(np.asarray(R_temp_mesh.vertex_normals))
util.regist_mesh_pcd(r_jerry_pcd, temp_pcd, R_temp_mesh_old)
o3d.visualization.draw_geometries([R_temp_mesh_old,R_temp_mesh, coord])